### ISSUE TITLE
Textbox component inside a Modal component loses focus after every keystroke

### ISSUE THREAD

**Issue by KazysKersulis** [sebgroup/react-components#388] opened 2020-05-27 08:09 UTC
**Describe the bug**
A Textbox component inside a Modal component loses focus after every keystroke when state is set and the component is redrawn.

**To Reproduce**
1. Add a Modal component
2. Inside the Modal component add a Textbox component
3. In the onChange method set the input state
4. Try writing in the Textbox component
5. see the bug (lost focus on the Textbox after every keystroke)

**Expected behavior**
Focus on the Textbox should not be lost after every keystroke

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
Adding the Textbox component with the same implementation outside the Modal works as expected without focus lost after every keystroke

**Comment by yousifalraheem** [comment] 2020-08-17 04:55
@KazysKersulis .. We were unable to reproduce the issue. We tried rendering a textbox inside a modal and it worked without any noticeable issue. Please retest with the latest version, if the issue persists, please include more details about how to reproduce it. Otherwise, you can close the issue.

**Closed** 2023-03-29 10:18 UTC
